### ISSUE TITLE
User accounts

### ISSUE THREAD

**Issue by CyanideLion** [CyanideLion/RezeptWebApp#8]
users being able to create/edit recipes

**Comment by zitrusgelb** [comment]
maybe use an oauth solution like keycloak, authentik, authelia

**Comment by zitrusgelb** [comment]
alternatively just use oidc from google and other platforms

**Comment by CyanideLion** [comment]
> alternatively just use oidc from google and other platforms
OIDC login implemented, should be working in test mode
